Polina devel
Attractadore/DataStructures pull request #1
Opened 2021-05-01 18:47 UTC by PolinaA2020

New pull request

2021-05-01 18:54 UTC, Attractadore commented on include/DataStructures/LRUCache.h
> +#include "BaseVector.h"
Move includes not used in header into source file

2021-05-01 18:57 UTC, Attractadore commented on include/DataStructures/LRUCache.h
> +void const* LRUgetNextData(LRUCache* LRU); // +-
See DummyCache.h

2021-05-01 18:57 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +typedef struct node_t DoubleListNode;
Maybe rename node_t to DoubleListNode_T?

2021-05-01 18:59 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +void doubleListPrepend(DoubleList* list);
Should be
void doubleListPrepend(DoubleList* list, DoubleListNode* node);

2021-05-01 19:01 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +void doubleListPrepend(DoubleList* list);
or
DoubleListNode* doubleListPrepend(DoubleList* list, DoubleListNode* node);

2021-05-01 19:12 UTC, PolinaA2020 commented on include/DataStructures/BaseDoubleList.h
> +void doubleListPrepend(DoubleList* list);
I dont understand what it does, why we send DoubleListNode* node. I thought it creates new node in front of the list. And doubleListAddFront calls doubleListPrepend, than memcpy in list->start->data

2021-05-01 19:32 UTC, Attractadore requested changes

2021-05-01 19:32 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +#include <string.h>
Move into source file

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	DoubleList* list = calloc(1, sizeof(DoubleList) + key_size);
What if calloc returns NULL?

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	assert(list && "DoubleList has not been defined!");
This message does not make any sense

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +}
doubleListPrepend(list, node) should add an existing node to the beginning of a list

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	memcpy(list->start->data, value, list->key_size);
Should be
DoubleListNode* node = calloc(1, sizeof(*node) + list->key_size);
if (!node) { ... }
memcpy(node->data, value, list->key_size);
return doubleListPrepend(list, node)

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	assert(list->end && "DoubleListNode is already empty!");
DoubleList, not DoubleListNode

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +		return NULL;
Set list->start to NULL

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	node->prev = NULL;
Should put this into doubleListRemove

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	list->length++; // update cur_size, maybe no need
No need

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	node->next->prev = node->prev;
What if node->prev or node->next is NULL?

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +	assert(list && "DoubleList is already empty!");
Passing NULL to free should be allowed.

2021-05-01 19:32 UTC, Attractadore commented on src/BaseDoubleList.c
> +		free(list->start);
Only ONE free.
node->data is in the same allocation as node.

2021-05-01 19:32 UTC, Attractadore commented on src/LRUCache.h
> +#include "BaseVector.h"
Move into source file

2021-05-01 19:32 UTC, Attractadore commented on src/LRUCache.h
> +void const* LRUgetNextData(LRUCache* LRU); // +-
See DummyCache.h

2021-05-01 19:32 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +typedef struct node_t DoubleListNode;
Maybe rename node_t to DoubleListNode_T

2021-05-01 19:35 UTC, Attractadore commented on src/BaseDoubleList.c
> +	node->next = list->start;
This should be a call to doubleListPrepend

2021-05-02 23:03 UTC, Attractadore commented on src/BaseDoubleList.c
> +	assert(list);
assert надо использовать для проверки логических ошибок.
Если у тебя calloc вернул NULL, это ошибка исполнения.
В таком случае тоже лучше вернуть NULL.

2021-05-02 23:04 UTC, Attractadore commented on src/BaseDoubleList.c
> +	// list->key_size = key_size;
Почему это закомментировано?

2021-05-02 23:06 UTC, Attractadore commented on src/BaseDoubleList.c
> +		return NULL;
А list->end обновить?

2021-05-02 23:12 UTC, Attractadore commented on src/BaseDoubleList.c
> +	return node;
Что-то здесь неправильное написано.
Если мы вырезаем из начала, то нам надо обновить list->start.
Если нет, то надо обновить node->prev->next.
Если мы вырезаем из конца, то нам надо обновить list->end.
Если нет, то надо обновить node->next->prev.

2021-05-03 09:05 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +	return node;
обновление начала и конца забыла. остальное написано, 90 91 строки

2021-05-03 09:07 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +		return NULL;
Это ветвление на случай единственного элемента. list->end освобождается и становится NULL. list->start так то тоже, они на один элемент указывали. Можно поменять проверку  на list->start == list->end

2021-05-03 09:10 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +	// list->key_size = key_size;
раскомментила, а почему мы аллоцируем list с добавкой key_size?  calloc(1, sizeof(DoubleList) + key_size); В этой структуре же нет массива

2021-05-03 09:15 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +	return node;
Исправила

2021-05-03 09:34 UTC, Attractadore commented on src/BaseDoubleList.c
> +		return NULL;
Как он становится NULL, если ты ему ничего не присваиваешь?

2021-05-03 09:34 UTC, Attractadore commented on src/BaseDoubleList.c
> +	// list->key_size = key_size;
Я не знаю. Никакой добавки здесь не надо.

2021-05-04 13:42 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +void doubleListShowList(DoubleList* list, TypeOfValue type);
Это можно спрятать в .с файл.
И в тестах инклюдить его, вместо .h.

2021-05-04 13:47 UTC, Attractadore commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
Это что такое?

2021-05-04 13:49 UTC, Attractadore commented on src/LRUCacheFixed.h
> +bool lruCacheContains(LRUCache* LRU, void const* key); // +-
LRUCache const* вместо LRUCache*

2021-05-04 13:51 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		return NULL;
В этих случаях надо еще почистить аллоцированные ранее LRU  и LRU->table

2021-05-04 13:52 UTC, Attractadore commented on src/LRUCacheFixed.h
> +CachePolicyAddResult lruCacheAddorReplace(LRUCache* LRU, void const* key, void const* replace)
void const* replace должен быть void* replace -- мы ведь что-то туда пишем

2021-05-04 14:13 UTC, Attractadore commented on src/LRUCacheFixed.c
> +	void const* old_key;
Это не нужно, когда у нас есть доступ к концу списка

2021-05-04 14:14 UTC, Attractadore commented on src/LRUCacheFixed.c
> +	if (LRU->capacity <= LRU->list->length) {
LRU->capacity >= LRU->list->length
всегда по определению

2021-05-04 14:14 UTC, Attractadore commented on src/LRUCacheFixed.c
> +	if (LRU->capacity <= LRU->list->length) {
Наверное здесь должно было быть просто == вместо <=

2021-05-04 14:17 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		baseOHTDelete(LRU->table, LRU->old_key);
Тут надо дописать doubleListBack(list), которая будет возвращать указатель на последний узел
И doubleListNodeData(node), которая будет возвращать node->data.
И тогда мы делаем baseOHTDelete(table, back_data)

2021-05-04 14:20 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		replace = LRU->old_key;
В replace мы пишем ключ, который удалили. То есть:
memcpy(replace, node_data, element_size)
раз element_size хранится в list, надо будет дописать функцию
doubleListItemSize(list)

2021-05-04 14:21 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		LRU->old_key = getKey(new_end->data); // get hash
Опять же, это поле просто не нужно, раз у нас есть доступ к концу списка

2021-05-04 14:26 UTC, Attractadore commented on src/LRUCacheFixed.c
> +}
table надо всегда освобождать вне зависимоти от того, IsEmpty она или нет.
Free должен без проблем принимать NULL, как обычный free.

2021-05-04 14:36 UTC, Attractadore commented on src/LRUCacheFixed.c
> +	if (LRU->capacity <= LRU->list->length) {
К list->length у тебя вообще не доступа,
поэтому надо написать doubleListSize(list)

2021-05-04 21:09 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
Попытка номер два сделать нормальный free... Как ты в вк написал сделала, оно работает.

2021-05-04 21:14 UTC, Attractadore commented
При чем здесь *next?

On Wed, May 5, 2021, 12:09 AM Alpatova Polina ***@***.***>
wrote:

> *@PolinaA2020* commented on this pull request.
> ------------------------------
>
> In src/BaseDoubleList.c
> <https://github.com/Attractadore/DataStructures/pull/1#discussion_r626109402>
> :
>
> > +	if (node->next == NULL) {
>
> +		list->end = node->prev;
>
> +		node->prev->next = NULL;
>
> +		return node;
>
> +	}
>
> +	node->prev->next = node->next;
>
> +	node->next->prev = node->prev;
>
> +	node->next = NULL;
>
> +	node->prev = NULL;
>
> +	return node;
>
> +}
>
> +/*------------------------------------------------------------------------------------------------------------------------------*/
>
> +void doubleListFree(DoubleList* list)
>
> +{
>
> +	if (list) {
>
> +		DoubleListNode* tmp = list->start, *next;
>
>
> Попытка номер два сделать нормальный free... Как ты в вк написал сделала,
> оно работает.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Attractadore/DataStructures/pull/1#discussion_r626109402>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG4OPCSL2GLL767HEULTB73TMBPABANCNFSM436STQQQ>
> .
>

2021-05-04 21:15 UTC, Attractadore commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
При чем здесь *next?

2021-05-04 21:20 UTC, Attractadore commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
А, я понял.

2021-05-04 21:21 UTC, Attractadore commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
Можешь, пожалуйста, перенести объявление в цикл?

2021-05-04 21:22 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
while (tmp) {
			next = tmp->next;
			free(tmp);
			tmp = next;
		}
название next такое себе, tmp_next... Я сначала без него сделала, используя tmp как next, а как tmp - list->start. Но освобождалось криво почему то

2021-05-04 21:31 UTC, PolinaA2020 commented on src/LRUCacheFixed.c
> +		replace = LRU->old_key;
а нельзя element_size получать как sizeof(back_data)? Это не одно и то же?

2021-05-04 21:33 UTC, Attractadore commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
Я просто к тому, что из
DoubleListNode* tmp = list->start, *next
лично мне ни фига не очевидно, что тут происходит объявление двух указателей,
а не чего-то другое.

2021-05-04 21:38 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		replace = LRU->old_key;
back_data это всегда void* (или unsigned char*, но лучше void*).
Так что нет

2021-05-04 21:39 UTC, PolinaA2020 commented on src/BaseDoubleList.c
> +		DoubleListNode* tmp = list->start, *next;
хорошо, поняла проблему. Только не в цикле, а перед циклом объявлю отдельной строкой

2021-05-06 10:09 UTC, Attractadore commented on include/DataStructures/BaseDoubleList.h
> +void const* doubleListNodeData(DoubleListNode* node);
void*, а не void const* -- мы хотим иметь возможность менять
для void const* можно (но не особо нужно) написать
doubleListNodeConstData(DoubleListNode const* node)

2021-05-06 10:25 UTC, Attractadore commented on src/BaseDoubleList.c
> +#include "BaseDoubleList.h"
Хорошо, когда инклюды идут в следующем порядке:
Свои заголовки
Заголовки чужих библиотек
Стандрартные заголовки

Все категории разделяются пустой. Идея в том, что расположенные сверху заголовки могут уже включать расположенные снизу, и тогда расположенные снизу можно легко почистить.

2021-05-06 10:29 UTC, Attractadore commented on src/LRUCacheFixed.h
> +bool lruCacheContains(LRUCache* LRU, void const* key); // +
Здесь у тебя почему-то перепутаны местами LRUCache const* и LRUCache*. Должно быть наоборот.

2021-05-06 10:29 UTC, PolinaA2020 commented on include/DataStructures/BaseDoubleList.h
> +void const* doubleListNodeData(DoubleListNode* node);
43(LRUCacheFixed.c):  void const* old_data = doubleListNodeData(old_end); 
Мы же используем эту функцию чтобы просто посмотреть key, и передать его в данном случае в void baseOHTDelete(BaseOHT* table, void const* key);

2021-05-06 10:30 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		lruCacheFree(LRU);
тут надо в случае ошибки еще и table чистить

2021-05-06 10:30 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		lruCacheFree(LRU);
в смысле после аллокации листа

2021-05-06 10:31 UTC, PolinaA2020 commented on src/LRUCacheFixed.c
> +		lruCacheFree(LRU);
lruCacheFree(LRU) чистит и таблицу, и список

2021-05-06 10:34 UTC, Attractadore commented on src/LRUCacheFixed.c
> +		lruCacheFree(LRU);
А, ну тогда хорошо

2021-05-06 10:36 UTC, PolinaA2020 commented on src/LRUCacheFixed.c
> +		lruCacheFree(LRU);
Ну я вызываю и после фейла в аллокации листа, и после фейла в аллокации таблицы lruCacheFree(LRU)

2021-05-06 10:36 UTC, PolinaA2020 commented on src/LRUCacheFixed.h
> +bool lruCacheContains(LRUCache* LRU, void const* key); // +
В BaseDoubleList.h добавила в функции типа NodeData DoubleList const*

2021-05-07 09:47 UTC, merged